Repository Team-StudyLog/StudyLog-BE, pull requests merged in 2025-08, with the labels that each got.

#28 [Feature/#26] 사용자 레벨 변경 이벤트 처리
  src/main/java/org/example/studylog/StudyLogApplication.java
  src/main/java/org/example/studylog/entity/user/LevelThresholds.java
  src/main/java/org/example/studylog/entity/user/User.java
  src/main/java/org/example/studylog/event/LevelEvent.java
  src/main/java/org/example/studylog/event/RecordEvent.java
  src/main/java/org/example/studylog/event/listener/LevelChangeListener.java
  src/main/java/org/example/studylog/event/listener/NotificationListener.java
  src/main/java/org/example/studylog/service/StudyRecordService.java
Labels: 💡Feature

#31 [Refactor/#30] 메인 페이지, 스트릭 수정사항
  src/main/java/org/example/studylog/controller/MainController.java
  src/main/java/org/example/studylog/controller/StreakController.java
  src/main/java/org/example/studylog/dto/MainPageResponseDTO.java
  src/main/java/org/example/studylog/service/MainService.java
  src/main/java/org/example/studylog/service/StreakService.java
  src/test/java/org/example/studylog/service/StudyRecordServiceTest.java
Labels: 🧽Chore, 📭 API

#32 [Refactor/#29] 인증 방식을 쿠키에서 헤더로 변경
  src/main/java/org/example/studylog/config/SecurityConfig.java
  src/main/java/org/example/studylog/controller/jwt/AuthController.java
  src/main/java/org/example/studylog/dto/oauth/TokenDTO.java
  src/main/java/org/example/studylog/jwt/JWTFilter.java
  src/main/java/org/example/studylog/oauth2/CustomSuccessHandler.java
  src/main/java/org/example/studylog/service/TokenService.java
Labels: 🔨 Refactor

#34 [Chore/#33] 일부 컨트롤러(API)에 Swagger 문서용 @Operation 및 @ApiResponse 추가
  src/main/java/org/example/studylog/config/SwaggerConfig.java
  src/main/java/org/example/studylog/controller/FriendController.java
  src/main/java/org/example/studylog/controller/NotificationController.java
  src/main/java/org/example/studylog/controller/QuizController.java
  src/main/java/org/example/studylog/controller/UserController.java
  src/main/java/org/example/studylog/controller/jwt/AuthController.java
  src/main/java/org/example/studylog/dto/oauth/TokenDTO.java
  src/main/java/org/example/studylog/oauth2/ProfileCheckFilter.java
Labels: 📄Docs, 🧽Chore

#35 [Refactor/#30] Streak API 응답 다듬기 & Swagger documentation
  .gitignore
  package-lock.json
  package.json
  src/main/java/org/example/studylog/controller/CategoryController.java
  src/main/java/org/example/studylog/controller/MainController.java
  src/main/java/org/example/studylog/controller/StreakController.java
  src/main/java/org/example/studylog/controller/StudyRecordController.java
  src/main/java/org/example/studylog/service/StreakService.java
Labels: 📄Docs, 🧽Chore

#38 [Feat/#37] CORS 설정
  src/main/java/org/example/studylog/config/CorsMvcConfig.java
  src/main/java/org/example/studylog/config/SecurityConfig.java
Labels: 💡Feature

#41 fix: main page follow check
  src/main/java/org/example/studylog/controller/MainController.java
  src/main/java/org/example/studylog/dto/MainPageResponseDTO.java
  src/main/java/org/example/studylog/service/MainService.java
Labels: 🔨 Refactor

#52 [Feat/#51] Servlet Cookie를 ResponseCookie로 변경
  src/main/java/org/example/studylog/controller/jwt/AuthController.java
  src/main/java/org/example/studylog/oauth2/CustomSuccessHandler.java
  src/main/java/org/example/studylog/util/CookieUtil.java
Labels: 💡Feature, 🔨 Refactor

#54 [Feat/#39] 회원 탈퇴 기능 구현
  build.gradle
  src/main/java/org/example/studylog/client/GoogleClient.java
  src/main/java/org/example/studylog/client/KakaoApiClient.java
  src/main/java/org/example/studylog/client/KakaoAuthClient.java
  src/main/java/org/example/studylog/config/HttpClientConfig.java
  src/main/java/org/example/studylog/config/SecurityConfig.java
  src/main/java/org/example/studylog/controller/UserController.java
  src/main/java/org/example/studylog/dto/oauth/OAuthTokenResponse.java
  src/main/java/org/example/studylog/entity/Friend.java
  src/main/java/org/example/studylog/entity/Streak.java
  src/main/java/org/example/studylog/entity/StudyRecord.java
  src/main/java/org/example/studylog/entity/category/Category.java
  src/main/java/org/example/studylog/entity/notification/Notification.java
  src/main/java/org/example/studylog/entity/quiz/Quiz.java
  src/main/java/org/example/studylog/entity/user/User.java
  src/main/java/org/example/studylog/oauth2/CustomSuccessHandler.java
  src/main/java/org/example/studylog/repository/RefreshRepository.java
  src/main/java/org/example/studylog/service/UserService.java
  src/main/java/org/example/studylog/service/oauth/CustomOAuth2UserService.java
  src/main/java/org/example/studylog/service/oauth/ExternalOAuthUnlinkService.java
  src/main/java/org/example/studylog/service/oauth/GoogleOAuthService.java
  src/main/java/org/example/studylog/service/oauth/KakaoOAuthService.java
  src/main/java/org/example/studylog/util/AesGcmEncryptor.java
  src/main/resources/db/migration/V1__add_column_to_users.sql
Labels: 💡Feature, 📭 API

#57 [Feat/#56] 로그아웃 API
  src/main/java/org/example/studylog/controller/UserController.java
  src/main/java/org/example/studylog/service/UserService.java
  src/main/resources/db/migration/V1__add_column_and_add_constraint.sql
Labels: 💡Feature, 📭 API
